# Generated by Django 5.1.1 on 2024-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('labelName', models.CharField(max_length=100)),
                ('labelCountry', models.CharField(max_length=100)),
                ('labelWebsite', models.TextField()),
                ('labelEmail', models.CharField(max_length=100)),
            ],
        ),
    ]
