# Generated by Django 5.1.1 on 2024-11-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('musiciannickname', models.TextField(db_column='musicianNickname')),
                ('musicianisverifiedv', models.BooleanField(db_column='musicianIsVerifiedV')),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
                'db_table': 'musicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musiclabels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('labelname', models.TextField(db_column='labelName')),
                ('labelweb', models.TextField(blank=True, db_column='labelWeb', null=True)),
                ('labellogo', models.TextField(blank=True, db_column='labelLogo', null=True)),
                ('labellocate', models.TextField(blank=True, db_column='labelLocate', null=True)),
            ],
            options={
                'verbose_name': 'Лейблы',
                'verbose_name_plural': 'Лейблы',
                'db_table': 'musicLabels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('playlistname', models.TextField(db_column='playlistName')),
                ('playlistpreview', models.TextField(blank=True, db_column='playlistPreview', null=True)),
            ],
            options={
                'verbose_name': 'Плейлисты',
                'verbose_name_plural': 'Плейлисты',
                'db_table': 'playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namesong', models.TextField(db_column='nameSong')),
                ('genre', models.TextField(blank=True, null=True)),
                ('audiofile', models.TextField(blank=True, db_column='audioFile', null=True)),
                ('songpreview', models.TextField(blank=True, db_column='songPreview', null=True)),
                ('songrealeasedatee', models.DateField(db_column='songRealeaseDatee')),
                ('songduration', models.DurationField(db_column='songDuration')),
            ],
            options={
                'verbose_name': 'Песни',
                'verbose_name_plural': 'Песни',
                'db_table': 'songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('username', models.TextField()),
                ('userdatereg', models.DateField(blank=True, db_column='userDateReg', null=True)),
                ('token', models.TextField()),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.playlists')),
            ],
            options={
                'verbose_name': 'ПлейлистПесни(смеж)',
                'verbose_name_plural': 'ПлейлистПесни(смеж)',
                'db_table': 'playlist_songs',
                'managed': False,
            },
        ),
    ]
